# Generated by Django 4.1.5 on 2023-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='power',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='speed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
