# Generated by Django 4.1.5 on 2023-01-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0002_carrera_power_carrera_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='power',
        ),
    ]
