# Generated by Django 4.1.5 on 2023-01-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0003_remove_carrera_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='speed',
        ),
    ]
